### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Windvis** [JLHwung/postcss-font-family-system-ui#197]
I started seeing the following error in our builds:
```
(node:20172) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at computePolyfillFlagFromStatus (/Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss-font-family-system-ui/index.bundle.js:18:33)
    at generatePolyfillFlags (/Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss-font-family-system-ui/index.bundle.js:79:32)
    at getSystemUiFamily (/Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss-font-family-system-ui/index.bundle.js:105:24)
    at /Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss-font-family-system-ui/index.bundle.js:139:21
    at LazyResult.run (/Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss/lib/lazy-result.js:221:14)
    at /Users/samvc/Development/Projects/ahlers/front-end/node_modules/postcss/lib/lazy-result.js:213:17
```

I did some debugging and it looks like an error is thrown when a browser version is unknown. (In our case, our browserlist returns ff 68, but the caniuse-db only knows about ff 67). [This line is the problem](https://github.com/JLHwung/postcss-font-family-system-ui/blob/10e0c49492e9058ac8247709b14c68792672584a/lib/get-system-ui-family.js#L30).

Updating the caniuse-lite dependency by deleting our node_modules and lock file seems to solve the problem, but it would be nice if this situation could be solved in code as well.

Maybe simply flagging the version as unsupported is good enough? I'm not familiar with the codebase though.

**Comment by JLHwung** [comment]
> Updating the caniuse-lite dependency by deleting our node_modules and lock file seems to solve the problem

Yes, caniuse-lite should always updated to the latest version. If you are using yarn, you can try [yarn-deduplicate], a handy tool that keeps your leaf dependencies up-to-dated.

[yarn-deduplicate]: https://github.com/atlassian/yarn-deduplicate#yarn-deduplicate

> when a browser version is unknown, ...maybe simply flagging the version as unsupported

There are two scenarios where browser version is unknown:
1) the caniuse-lite is not up-to-dated
2) user specifies a custom browser that caniuse-lite does not even support

For the first scenario we should better mark as supported otherwise the user will experience an unexpected long list of system-ui polyfills. For the second we say it is unsupported because we can't know the support status from compile time.
