### ISSUE TITLE
Errors When Running Jest Unit Tests

### ISSUE THREAD

**Issue by pahund** [JLHwung/postcss-font-family-system-ui#37]
We have a project that uses Express, React, [postcss-cssnext](https://github.com/MoOx/postcss-cssnext) and Jest unit tests.

Since 9. January 2018, when we run our tests, we get multiple errors on varying tests. All have the same stack trace:

    TypeError: Cannot read property 'filename' of undefined

      at Function.Object.<anonymous>.Module._load (node_modules/mock-require/index.js:12:49)
      at Module.require (module.js:497:17)
      at Object.<anonymous> (node_modules/@std/esm/index.js:1:1466)
      at i (node_modules/@std/esm/index.js:1:1090)
      at Object.<anonymous> (node_modules/@std/esm/index.js:1:1509)
      at i (node_modules/@std/esm/index.js:1:1090)
      at Object.<anonymous> (node_modules/@std/esm/index.js:1:165398)
      at i (node_modules/@std/esm/index.js:1:1090)
      at node_modules/@std/esm/index.js:1:1428
      at node_modules/@std/esm/index.js:1:1439
      at load (node_modules/@std/esm/index.js:33:3)
      at Object.<anonymous> (node_modules/@std/esm/index.js:42:10)
      at Object.<anonymous> (node_modules/postcss-font-family-system-ui/src/index.js:2:11)
      at Object.fontFamilySystemUi (node_modules/postcss-cssnext/lib/features.js:96:12)
      at node_modules/postcss-cssnext/lib/index.js:79:44
      at Array.forEach (native)
      at node_modules/postcss-cssnext/lib/index.js:65:35
      at creator (node_modules/postcss/lib/postcss.js:150:35)
      at Object.<anonymous> (scripts/utils/setup-jest.js:27:5)
      at next (native)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:744:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

After some research, my colleague and I have found that there was a patch release 2.1.2 of _postcss-font-family-system-ui_ on the same day that the builds started failing.

_Postcss-cssnext_ has a minor-level dependency to _postcss-font-family-system-ui_, version 2.0.1, so a new, clean build pulled in the faulty module.

As a workaround, we've fixed our build for now by adding a exact-version dev dependency to our project:

    npm install --save-dev --save-exact postcss-font-family-system-ui@2.0.1

I've opened up a ticket for [postcss-cssnext](https://github.com/MoOx/postcss-cssnext/issues/439), but its [maintainer](https://github.com/MoOx) thinks this problem should be fixed on the end of this project (and I agree with him).

**Comment by JLHwung** [comment]
Hi, I notice that the error is thrown on `mock-require`, I am wondering how you use `mock-require` in your repo. Is `require('mock-require')` on jest `setupFiles`? And how `jest` call the `postcss` routine which invokes `postcss-font-family-system-ui`?

The biggest change of `postcss-font-family-system-ui` since 2.1.0 is the introduction of [@std/esm](https://github.com/standard-things/esm). While I am almost sure there must be some compatibility issues between `esm` and `mock-require`. It would of great help if there is a minimal reproducing repo/snippets.

Before this issue is resolved, I recommend to pin the version to 2.0.1. Once the issue is narrow down, I can file an issue to esm or mock-require.

**Comment by pahund** [comment]
Strangely, we are using mock-require only for our legacy Mocha tests, not for Jest. So no, it's not in the Jest setup file. The Mocha tests run just fine, the Jest tests fail, even when run independently from the Mocha tests.

The Jest setup file includes PostCSS like this:

    const hook = require('css-modules-require-hook');
    const cssnext = require('postcss-cssnext');

    const cssVariables = require('@mt-ui/theme');

    hook({
        extensions: ['.css'],
        prepend: [
            cssnext({
                browsers: ['last 2 versions', '> 5%'],
                features: {
                    customProperties: {
                        variables: cssVariables
                    }
                }
            })
        ]
    });

**Comment by pahund** [comment]
💯 I can confirm that the issue is fixed, my Jest tests run as smoothly as ever. **Thank you very much, and keep up the great work!** 💯
